# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'SDK v5.0.x'
  inputs:
    version: '5.0.x'
    performMultiLevelLookup: true
    includePreviewVersions: true # Required for preview versions

- task: UseDotNet@2
  displayName: 'Runtime v3.0.x'
  inputs:
    version: '3.0.x'
    packageType: runtime

# ...
# do this after other tasks such as building
- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'